server:
  port: 8872
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8
  error:
    include-message: always
    include-stacktrace: always

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 40
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: 'jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mapstruct_taya}'
